## Essential numpy commands/operations used

In [2]:
import numpy as np

In [3]:
np.__version__

'1.13.3'

In [4]:
# create integer array from lists
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
# if data is not the same type, python will cast
np.array([1,2,3,4.0])

array([ 1.,  2.,  3.,  4.])

In [6]:
# set data type required
np.array([1,2,3,4.0],dtype='int')

array([1, 2, 3, 4])

In [7]:
a = np.array([1,2,3,4])

In [8]:
print(a.shape)
print(a.dtype)
print(a.size)

(4,)
int64
4


In [9]:
b = np.array([range(i,i+3) for i in range(2,5)])

In [10]:
print(b)
print(b.shape)
print(b.size)
print(b.dtype)

[[2 3 4]
 [3 4 5]
 [4 5 6]]
(3, 3)
9
int64


In [11]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
np.ones(10, dtype='int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
np.ones(dtype='int', shape=(2,3))

array([[1, 1, 1],
       [1, 1, 1]])

### Array Operations

In [15]:
print(a)
print
print(b)

[1 2 3 4]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [16]:
c = b*2

In [17]:
print(c)

[[ 4  6  8]
 [ 6  8 10]
 [ 8 10 12]]


In [18]:
# Dimensions must be same
d = b+c

In [19]:
print(d)

[[ 6  9 12]
 [ 9 12 15]
 [12 15 18]]


In [20]:
d[0]

array([ 6,  9, 12])

In [21]:
d[0][1]

9

In [22]:
d[0,1]

9

In [23]:
d[1:3]

array([[ 9, 12, 15],
       [12, 15, 18]])

In [24]:
d[:3]

array([[ 6,  9, 12],
       [ 9, 12, 15],
       [12, 15, 18]])

In [25]:
d[:2,:1]

array([[6],
       [9]])

In [26]:
d[:2,:3]

array([[ 6,  9, 12],
       [ 9, 12, 15]])

In [27]:
d.mean()

12.0

In [28]:
# vertical axis
d.mean(axis=0)

array([  9.,  12.,  15.])

In [29]:
# horizontal axis
d.mean(axis=1)

array([  9.,  12.,  15.])

In [30]:
# vertical axis
d.sum(axis=0)

array([27, 36, 45])

In [31]:
# horizontal axis
d.sum(axis=1)

array([27, 36, 45])

In [32]:
d.sum()

108

### Reshape and update in-place

In [33]:
e = np.arange(12)

In [34]:
print(e)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [35]:
e.resize(10)

In [36]:
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [37]:
e.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
e.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [39]:
f=e.reshape(2,5)

In [40]:
f.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [41]:
print(a)
print
print(b)
print
print(c)
print
print(d)

[1 2 3 4]

[[2 3 4]
 [3 4 5]
 [4 5 6]]

[[ 4  6  8]
 [ 6  8 10]
 [ 8 10 12]]

[[ 6  9 12]
 [ 9 12 15]
 [12 15 18]]


In [42]:
np.concatenate([a,a])

array([1, 2, 3, 4, 1, 2, 3, 4])

In [43]:
np.concatenate([b,c])

array([[ 2,  3,  4],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 4,  6,  8],
       [ 6,  8, 10],
       [ 8, 10, 12]])

In [44]:
np.vstack([b,c])

array([[ 2,  3,  4],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 4,  6,  8],
       [ 6,  8, 10],
       [ 8, 10, 12]])

In [45]:
np.hstack([b,c])

array([[ 2,  3,  4,  4,  6,  8],
       [ 3,  4,  5,  6,  8, 10],
       [ 4,  5,  6,  8, 10, 12]])